version: '3.7'

services:

  vlmcsd:
    image: vlmcsd
    build: 
      context: .
      dockerfile: Dockerfile-vlmcsd
    ports: 
      - "1688:1688"
    init: true
    volumes:
      - "./logs:/mnt/log/"
    command: sh -c "(/observer.sh &) && /vlmcsd -D -d -t 3  -v -l /mnt/log/logs "

  kmsbackend:
    image: kmsbackend
    build: 
      context: .
    ports:
      - "5000:5000"
    volumes:
      - "./logs:/mnt/log/"
      - "./uwsgi/:/mnt/uwsgi/"
    links:
      - vlmcsd




